spring:
  application:
    name: note
  datasource:
    write:
      jdbc-url: jdbc:postgresql://localhost:6432/motion-db?autoReconnect=true #write-pgbouncer-host:6432
      username: postgres
      password: zxca
      driver-class-name: org.postgresql.Driver
      hikari:
        pool-name: write-pool
        maximum-pool-size: 20
    read:
      jdbc-url: jdbc:postgresql://localhost:6433/motion-db?autoReconnect=true #33
      username: postgres
      password: zxca
      driver-class-name: org.postgresql.Driver
      hikari:
        pool-name: read-pool
        maximum-pool-size: 40
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      temp.use_jdbc_metadata_defaults: false
      hbm2ddl.auto: none
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  kafka:
    producer:
      bootstrap-servers: localhost:29092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

  data:
    redis:
      host: localhost
      port: 6379

cloud:
  aws:
    credentials:
      access-key: ${AWS_ACCESS_KEY_ID}
      secret-key: ${AWS_SECRET_ACCESS_KEY}
    region: eu-north-1
    s3:
      bucket-name: motion-note-content


server:
  port: 8073